spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/Votaciones
    username: postgres
    password: postgres2023
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: votaciones_senado   # ðŸ”¥ Esto asegura que TODOS los INSERT vayan a votaciones_senado

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: votaciones_senado   # ðŸ”¥ Hibernate generarÃ¡ y buscarÃ¡ tablas en este esquema
        format_sql: true
        globally_quoted_identifiers: false
        jdbc.lob.non_contextual_creation: true

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.thymeleaf: TRACE
