name: CI-CD - Tests + Sonar + Deploy JAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # CI: Build + Tests + Coverage
      - name: Build & Test (JUnit + Cucumber + Jacoco)
        run: mvn -B clean verify

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: |
            target/**/*.html
            target/**/*.json
          if-no-files-found: warn

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B sonar:sonar
          -Dsonar.organization=ivonnelizethmoreno-cloud
          -Dsonar.projectKey=ivonnelizethmoreno-cloud_SistemaElectoralFinal
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.branch.name=master
          -Dsonar.tests=src/test/java
          -Dsonar.junit.reportPaths=target/surefire-reports
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          -Dsonar.cucumber.reportPaths=target/cucumber.json


  # -------------------------------------------------------
  #  CD: Generar y publicar JAR como artefacto de despliegue
  # -------------------------------------------------------
  deploy:
    needs: build        # Solo corre si el CI pas√≥ correctamente
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Generar el JAR final
      - name: Build Deployable JAR
        run: mvn -B clean package -DskipTests

      # Guardar el JAR como artefacto de CD
      - name: Upload Deployable Artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          if-no-files-found: error
