name: CI - Tests + Cucumber + SonarCloud

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:

      # 1. Código fuente
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3. Compilar sin ejecutar pruebas todavía
      - name: Build Project
        run: mvn -B clean package -DskipTests

      # 4. Ejecutar pruebas unitarias + Jacoco
      - name: Run Unit Tests + Jacoco
        run: |
          mvn -B test
          mvn -B org.jacoco:jacoco-maven-plugin:0.8.11:report

      # 5. Ejecutar Cucumber Tests
      - name: Run Cucumber Tests
        run: mvn -B test

      # 6. Publicar reportes Cucumber
      - name: Publicar reporte Cucumber
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: |
            target/**/*.html
            target/**/*.json
          if-no-files-found: warn

      #- name: SonarCloud Scan
       # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #run: |
         #  mvn -B verify sonar:sonar \
          #   -Dsonar.organization=ivonnelizethmoreno-cloud \
           #  -Dsonar.projectKey=SistemaElectoralFinal \
            # -Dsonar.host.url=https://sonarcloud.io \
            # -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            # -Dsonar.branch.name=main \
            # -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
