name: CI - Tests + Cucumber + SonarCloud

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:

      # 1. Código fuente
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Compilar sin ejecutar pruebas todavía
      #- name: Build Project
       # run: mvn -B clean package -DskipTests
# habrá que compilar y empaquetar el proyecto cuando el 
# pom.xml esté integro proximas 2 lines, vamos a comentariar
# lines 30 and 31 y habilitar 35 y 36
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

      # 4. Ejecutar pruebas unitarias + Jacoco
      - name: Run Unit Tests + Jacoco
        run: |
          mvn -B test
          mvn -B org.jacoco:jacoco-maven-plugin:0.8.11:report

      # 5. Ejecutar Cucumber Tests
     # - name: Run Cucumber Tests
      #  run: mvn -B test
# vamos a probar corriendo cucumber junit 5 hasta que estén las
# dependencias es nuestro pom.xml serán las proximas 7 lines
# vamos a comentariar lines 45 & 46 y habilitar 50 a 56
    - name: Run Cucumber (JUnit 5)
      run: |
       mvn -B -ntp test \
       -Dtest=com.grupo.RunCucumberTest \
       -Dcucumber.features=src/test/resources/features \
       -Dcucumber.execution.strict=false \
       -Dcucumber.plugin="pretty,html:target/cucumber-report.html,json:target/cucumber.json"


      # 6. Publicar reportes Cucumber
      - name: Publicar reporte Cucumber
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: |
            target/**/*.html
            target/**/*.json
          if-no-files-found: warn

      # 7. SonarCloud Scan
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.organization=ivonnelizethmoreno-cloud \
            -Dsonar.projectKey=ivonnelizethmoreno-cloud_SistemaElectoralFinal \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.branch.name=master \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
