name: CI - Tests + Cucumber + SonarCloud + CD JAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1. CÃ³digo fuente
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Ejecutar TODAS las pruebas + Jacoco + Cucumber
      - name: Run JUnit + Cucumber + Jacoco
        run: mvn -B clean verify

      # 4. Construir JAR ejecutable (Spring Boot repackage)
      - name: Build Executable JAR
        run: mvn -B package -DskipTests

      # 5. Subir el JAR como artifact (esto es el CD)
      - name: Upload Executable JAR
        uses: actions/upload-artifact@v4
        with:
          name: sistema-electoral-jar
          path: target/*.jar
          if-no-files-found: error

      # 6. Subir reportes de Cucumber
      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: |
            target/**/*.html
            target/**/*.json
          if-no-files-found: warn

      # 7. SonarCloud
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B sonar:sonar
          -Dsonar.organization=ivonnelizethmoreno-cloud
          -Dsonar.projectKey=ivonnelizethmoreno-cloud_SistemaElectoralFinal
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.branch.name=master
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
